In [1]:
import pandas as pd
df = pd.read_parquet('/Users/darcor/Data/EDP Thesis/Output/Photovoltaic_rcp_8_5.parquet', engine="fastparquet")

In [2]:
df['Celsius'] = df['t2m'] - 273.15

In [3]:
df.dropna(subset=['Celsius'], inplace=True)

In [5]:
df['Year'] = df['time'].dt.year

In [7]:
df.groupby(["Year"]).agg(
    mean_temp=('Celsius', 'mean'),
    min_temp=('Celsius', 'min'),
    max_temp=('Celsius', 'max'),
    count=('Celsius', 'count')
).reset_index()

    Year  mean_temp   min_temp   max_temp  count
0   2025  14.619952  -4.877899  43.324402  32109
1   2026  14.028624  -5.360596  40.099182  32120
2   2027  14.505062 -10.042267  45.063965  32120
3   2028  13.610561  -5.372101  40.479156  32208
4   2029  13.619565  -5.508179  38.653595  32120
5   2030  14.436131  -4.284058  41.717346  32120
6   2031  14.191820  -5.201294  41.604248  32120
7   2032  15.439136  -5.314850  42.266083  32208
8   2033  14.112773  -5.191223  43.054321  32120
9   2034  14.965340  -6.607971  40.956207  32120
10  2035  14.687211  -4.936127  41.876160  32120
11  2036  14.543899  -5.764099  42.468140  32208
12  2037  15.584441  -5.666962  44.710876  32120
13  2038  14.213802  -5.601471  42.397156  32120
14  2039  14.814881  -5.942993  43.453979  32120
15  2040  15.768423  -5.640045  43.236542  32208
16  2041  14.965753  -4.215210  43.888550  32120
17  2042  15.986364  -3.317627  40.707245  32120
18  2043  15.238041  -4.678162  42.922424  32120
19  2044  14.566588  -3.471893  40.444031  32208
20  2045  14.689818  -4.499573  39.259277  32120
21  2046  15.094666  -4.622681  41.081421  32120
22  2047  15.113360  -3.915222  44.154388  32120
23  2048  15.044933  -5.395996  41.740051  32208
24  2049  12.502460   7.501221  15.097015     11